version: "3.9"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: builderscalc:web
    ports:
      # Local dev: visit http://localhost:8080
      - "8080:80"
    environment:
      NODE_ENV: production
      PORT: "80"
      SITE_DIR: /app/site
      SETTINGS_PATH: /data/settings.json
      # SMTP configuration (uncomment and set via .env or inline)
      # SMTP_HOST: mail.smtp2go.com
      # SMTP_PORT: "2525"
      # SMTP_SECURE: "false"
      # SMTP_USERNAME: "${SMTP_USERNAME}"
      # SMTP_PASSWORD: "${SMTP_PASSWORD}"
      # CONTACT_FROM_EMAIL: "no-reply@your-domain"
      # CONTACT_TO_EMAIL: "zeke@rootsandecho.co.nz"
      # CONTACT_REPLY_TO: "zeke@rootsandecho.co.nz"
    volumes:
      # Named volume for persistent settings file
      - data:/data
    restart: unless-stopped
    # Local healthcheck using Node (no curl/wget required)
    healthcheck:
      test: ["CMD", "node", "-e", "require('http').get('http://localhost/health',res=>process.exit(res.statusCode===200?0:1)).on('error',()=>process.exit(1))"]
      interval: 10s
      timeout: 3s
      retries: 5
      start_period: 10s

volumes:
  data:
